### PR TITLE
Animate item rotation

### LINKED ISSUE #69: Random offset and rotation extent should be adjustable
_Commit or branch_: master

#### Observed behavior

- Currently when `pileAlignment: false` we apply a random x,y offset and if `itemRotated: true` a random rotation with a **fixed** range of [[-30,30]](https://github.com/flekschas/piling.js/blob/master/src/pile.js#L372-L373) and [[-10,10]](https://github.com/flekschas/piling.js/blob/master/src/pile.js#L372-L373)

#### Expected behavior

- The random x,y offset and random rotation range should be adjustable via `set('randomOffsetRange', [min, max])` and `set('randomRotationRange', [min, max])`

### PR DESCRIPTION
**Pull request by eeeeenchanted**
## Description

> What was changed in this pull request?

Add `randomOffsetRange` and `randomRotationRange` to Redux store.

Animate item rotation when piling up and depiling.

> Why is it necessary?

Fixes #69 and #75.

## Checklist

- [x] GitHub labels properly set (e.g., bug, new feature, etc.)
- [x] Documentation added or updated
- [ ] Examples added or updated
- [ ] Screenshot or GIF included (e.g. new or changed visualization features)
- [x] CHANGELOG.md updated

### CODE REVIEW

File: src/item.js [hunk 1]
```diff
@@ -21,7 +21,6 @@ const createItem = (id, texture, preview, pubSub) => {
     clonedSprite.y = sprite.y;
     clonedSprite.width = sprite.width;
     clonedSprite.height = sprite.height;
-    clonedSprite.angle = sprite.angle;
```
Comment (flekschas) [inline src/item.js]: Just curious, why do we not clone the angle anymore?

Comment (eeeeenchanted) [reply src/item.js]: Actually I don't remember why we clone the angle 😂If the angle is cloned, when temp-depile, the cloned sprite will also be rotated. But I think the cloned sprite doesn't need to be rotated?
