### PR TITLE
Data-driven 1D and 2D layout arrangments

### LINKED ISSUE #63: Support automatic and data-driven layouts
Piling.js should support automatic and data-driven layouts. Similar to other automatic properties like `pileOpacity` the idea is that the user specifies an objective function that determines the pile position based on the items on the tile.

The endpoint to define the data-driven layout should look as follows:

```javascript
piling.arrangeBy(type, dataOrObjectionFunction, options);

// For one-time arrangement with the same signature as above
piling.arrangeByOnce(...)
```

Where `type` can be one of the following:
- `undefined` or `null`: Default. Piles are initially ordered by their index and are not automatically moved.
- `"data"`: Data-driven layout. Piles are position is derived from pile properties.
- `"index"`: Custom layout. A callback function returns the pile index.
- `"ij"`: Custom layout. A callback function returns the cell (i.e., ij position) the pile should be positioned in.
- `"xy"`: Custom layout. A callback function returns the final xy position.
- `"uv"`: Custom layout. A callback function returns the final uv position. UVs are like texture coordinates and go from `[0,0]` (top left corner of the canvas) to `[1,1]` (bottom right corner of the screen)

### Type: Data
When `type === 'data'`, `data` can either be a string, array, object, or function to produce a linear ordering, 2D scatterplot, or multi-dimensional cluster plot.

**1D / Linear Ordering:**

```javascript
// The following 4 calls are all equivalent but they should demonstrate the different extents of customizability
piling.arrangeBy('data', 'a');
piling.arrangeBy('data', pile => pile.a); // The user could specify a custom accessor/getter function
piling.arrangeBy(
  'data',
   {
      property: pile => pile.a,
      inverse: true // For descending order
    }
);
```

Also, in all 3 examples from above `data` could be wrapped in an array and the result should be identical because a single pile property can only lead to a linear ordering.

**2D Scatterplot:**

```javascript
piling.arrangeBy('data', ['a', 'b']); // `a` is used for the x-axis and `b` is used for the y-axis
piling.arrangeBy(
  'data',
  [
    {
      property: 'a',
      inverse: true
    },
    {
      property: pile => pile.a + pile.b,
      scale: d3.scaleLog  // Providing a scale function would be the highest level of customizability
    }
  ]
);
```

**Multi-dimensional Cluster Plot:**

```javascript
piling.arrangeBy('data', ['a', 'b', 'c']); // Will use t-SNE or UMAP automatically
piling.arrangeBy('data', pile => pile.src, { dimensionalityReduction: true }); // To use t-SNE or UMAP explicitely
```

### Type: index, ij, xy, uv

For complete freedom, it should also be possible to dynamically specify the index, ij, or xy position via pile-based callback functions

```javascript
piling.arrangeBy('index', pile => pile.id);
piling.arrangeBy('ij', pile => [pile.id - 1, pile.id + 1]);
piling.arrangeBy('xy', pile => [pile.id - 1, pile.id + 1]);
piling.arrangeBy('uv', pile => [pile.id - 1 / , pile.id + 1]);
```

### LINKED ISSUE #68: pile.positionItems() needs to be refactored
_Commit or branch_: master

_Code_: https://github.com/flekschas/piling.js/blob/master/src/pile.js#L315-L401

#### Observed behavior

- No alignment and a specific alignment are currently treated differently but technically they are very similar. The only difference is that the x,y offset is either generated randomly or in a deterministic fashion.

#### Expected behavior
- Both should use the same code for everything except for determining the x,y offset

### LINKED ISSUE #85: Support panning & zooming for navigation
Currently, we only support scroll-based view navigation. There should be a second option to switch to pan&zoom.

**Why?**

- This would be super useful for dense cluster views where you only want to look at a certain region.
- Automatic piling with pan&zoom is essentially _Scalable Insets_

### PR DESCRIPTION
**Pull request by eeeeenchanted**
## Description

> What was changed in this pull request?

Add a new method to the library to support automatic and data-driven layout.
```
piling.arrangeBy(type, dataOrObjectionFunction, options);
```
Add 2 properties `arrangementType` and `arrangementObjective` to store `type` and `dataOrObjectionFunction`. Use these properties to automatically position piles.

> Why is it necessary?

Fixes #63 
Fixes #68 
Fixes #85 

## Checklist

- [x] GitHub labels properly set (e.g., bug, new feature, etc.)
- [x] Documentation added or updated
- [ ] Examples added or updated
- [ ] Screenshot or GIF included (e.g. new or changed visualization features)
- [x] CHANGELOG.md updated

## Update

**Implemented features in this PR**
- Arrange by data
  - 1D ordering with scrolling
  - 2D scatterplots with pan&zoom
- Arrange by index, ij, xy, uv position

**Missing features in this PR**
- Multi-dimensional arrangement
- `piling.arrangeByOnce()`
- Refactor `pile.positionItems()`

The missing features will be addressed in other PRs.

### CODE REVIEW

**Comment by eeeeenchanted** [comment]
I've started implemented this with _Type: index, ij, xy, uv_. I also added a pile move animation, but the animation still has some problems when depiling. Because depiling will create new piles, and their original position is [0, 0], the animation will start at [0, 0].
Jan-19-2020 21-35-51

File: src/grid.js [hunk 1]
```diff
@@ -108,6 +108,17 @@ const createGrid = (
...
   };
 
+  /**
+   * Convert the u,v position to an x,y pixel position
+   * @param   {number}  u  Relative position of the canvas on the x-axis
+   * @param   {number}  v  Relative position of the canvas on the y-axis
+   * @return  {array}  Tuple representing the x,y position
+   */
+  const uvToXy = (u, v) => {
+    const { height } = canvas.getBoundingClientRect();
```
Comment (flekschas) [inline src/grid.js]: I think we can safely move this expression out of `uvToXy` because we'd have to update the entire grid anyway when the height changes otherwise positions would be out of sync.

File: src/library.js [hunk 2]
```diff
@@ -1593,6 +1646,13 @@ const createPilingJs = (rootElement, initOptions = {}) => {
     // Consequential updates that cause new actions to be dispatched
     if (stateUpdates.has('grid')) {
       updateGrid();
+    } else if (stateUpdates.has('arrange')) {
```
Comment (flekschas) [inline src/library.js]:
```suggestion
    }
    if (stateUpdates.has('arrange')) {
```

Why `else if`? The two changes aren't mutually exclusive are they?

File: src/library.js [hunk 3]
```diff
@@ -1625,6 +1685,15 @@ const createPilingJs = (rootElement, initOptions = {}) => {
     resetPileBorder();
   };
 
+  const arrangeBy = (type, dataOrObjectionFunction) => {
```
Comment (flekschas) [inline src/library.js]:
```suggestion
  const arrangeBy = (type, objective) => {
```

File: src/library.js [hunk 4]
```diff
@@ -1625,6 +1685,15 @@ const createPilingJs = (rootElement, initOptions = {}) => {
...
+    store.dispatch(
+      batchActions([
+        ...set('arrangementType', type, true),
+        ...set('arrangementObjective', dataOrObjectionFunction, true)
```
Comment (flekschas) [inline src/library.js]:
```suggestion
        ...set('arrangementObjective', objective, true)
```

File: src/pile.js [hunk 5]
```diff
@@ -694,6 +694,9 @@ const createPile = ({ initialItem, render, id, pubSub, store }) => {
 
     graphics.interactive = true;
     graphics.buttonMode = true;
+
+    initialItem.moveTo(0, 0);
```
Comment (flekschas) [inline src/pile.js]: I don't think we need this. If I am not mistaken `[0,0]` is the default position anyway

File: src/library.js [hunk 6]
```diff
@@ -1593,6 +1646,13 @@ const createPilingJs = (rootElement, initOptions = {}) => {
     // Consequential updates that cause new actions to be dispatched
     if (stateUpdates.has('grid')) {
       updateGrid();
+    } else if (stateUpdates.has('arrange')) {
+      changedPiles.forEach(id => {
+        const pile = pileInstances.get(id);
+        if (pile) {
```
Comment (flekschas) [inline src/library.js]: This can be written as follows to be more declarative:

```changedPiles.filter(id => pileInstances.has(id)).forEach(id => arrangePile(pileInstances.get(id)));```

Technically both are the same but the current code is a bit too imperative.

File: src/library.js [hunk 7]
```diff
@@ -1427,6 +1474,8 @@ const createPilingJs = (rootElement, initOptions = {}) => {
     const stateUpdates = new Set();
     const newlyCreatedItems = [];
 
+    const changedPiles = [];
```
Comment (flekschas) [inline src/library.js]:
```suggestion
    const updatedPiles = [];
```

Just for semantic consistency :)

File: src/library.js [hunk 8]
```diff
@@ -1449,13 +1498,17 @@ const createPilingJs = (rootElement, initOptions = {}) => {
           if (pile.items.length !== state.piles[id].items.length) {
             updatePileItems(pile, id);
             updatePileStyle(pile, id);
+            changedPiles.push(id);
```
Comment (flekschas) [inline src/library.js]:
```suggestion
            updatedPiles.push(id);
```

File: src/library.js [hunk 9]
```diff
@@ -1449,13 +1498,17 @@ const createPilingJs = (rootElement, initOptions = {}) => {
...
+            stateUpdates.add('arrange');
```
Comment (flekschas) [inline src/library.js]: I don't think we actually need this as `updatedPiles.length > 0` will be the same as `stateUpdates .has('arrange')`

File: src/library.js [hunk 10]
```diff
@@ -1449,13 +1498,17 @@ const createPilingJs = (rootElement, initOptions = {}) => {
...
           }
           if (
             (pile.x !== state.piles[id].x || pile.y !== state.piles[id].y) &&
             pile.items.length !== 0
           ) {
             updatePilePosition(pile, id);
             updatePileStyle(pile, id);
+            changedPiles.push(id);
```
Comment (flekschas) [inline src/library.js]:
```suggestion
            updatedPiles.push(id);
```

File: src/library.js [hunk 11]
```diff
@@ -620,6 +617,53 @@ const createPilingJs = (rootElement, initOptions = {}) => {
     );
   };
 
+  const arrangePile = pile => {
```
Comment (flekschas) [inline src/library.js]: Can we rename this function to `getPilePosition`?

File: src/library.js [hunk 12]
```diff
@@ -620,6 +617,53 @@ const createPilingJs = (rootElement, initOptions = {}) => {
...
+    }
+
+    if (i !== null) {
+      [x, y] = layout.ijToXy(i, j, pile.graphics.width, pile.graphics.height);
+    } else if (u !== null) {
+      [x, y] = layout.uvToXy(u, v);
+    }
+
+    if (x !== null) {
+      store.dispatch(createAction.movePiles([{ id: pile.id, x, y }]));
```
Comment (flekschas) [inline src/library.js]: Doesn't this cause `movePiles` to be dispatched twice when this function is called by `positionPiles`?

File: src/library.js [hunk 13]
```diff
@@ -629,27 +673,31 @@ const createPilingJs = (rootElement, initOptions = {}) => {
...
+          layout.numRows = j + 1;
 
-        movingPiles.push({ id, x, y });
+          [x, y] = layout.ijToXy(
+            i,
+            j,
+            pile.graphics.width,
+            pile.graphics.height
+          );
+          movingPiles.push({ id, x, y });
```
Comment (flekschas) [inline src/library.js]: I think this condition should be part of `getPilePosition`. This function should only have to deal with calling `getPilePosition()` for every pile, dispatching the `movePiles` action, and updating `layout.numRows`

File: src/library.js (hunk 12 above)
Comment (eeeeenchanted) [reply src/library.js]: In `positionPiles`, if the return value `[x. y]` from `getPilePosition` is not null, it won't dispatch `movePiles` again. See line 703-705.

File: src/library.js (hunk 13 above)
Comment (eeeeenchanted) [reply src/library.js]: Hmm, this condition is when `type` is `undefined` or `null`, the piles are initially positioned once and are not automatically moved, so I didn't put this condition in `getPilePosition()`.

**Comment by eeeeenchanted** [comment]
I started to implement as you said in #63. Can you review it when you have time? Thanks!

Two questions:
1. How can we store the properties in the `data` we loaded? Now we just use the `src` property to render the items. In your example, we actually can't get `item => item.numViews` because it's not a property of the item.
2. With 1D linear ordering, `dataScales` only has one scale function with a range of canvas width, so we can only get the `x` position of the piles using `dataScales`. What about the `y` position?

File: src/library.js [hunk 14]
```diff
@@ -1625,6 +1723,84 @@ const createPilingJs = (rootElement, initOptions = {}) => {
...
+        expandedObjective.aggregator = values =>
+          values.reduce((average, value) => average + value / values.length, 0);
+        expandedObjective.scale = scaleLinear;
+        expandedObjective.inverse = false;
+      } else {
+        expandedObjective.property = expandProperty(objective.property);
+
+        switch (objective.aggregator) {
+          case 'max':
+            expandedObjective.aggregator = values => Math.max(...values);
```
Comment (flekschas) [inline src/library.js]: Can you turn this into a utility function called `mean` to `utils.js`? I am sure we might use it elsewhere.

```javascript
export const max = array => array.reduce((max, v) => v > max ? v : max, -Infinity);
```

I've tested both your version and the reduce-based version and somehow the reduce-based version is 50% faster.

File: src/library.js [hunk 15]
```diff
@@ -1625,6 +1723,84 @@ const createPilingJs = (rootElement, initOptions = {}) => {
...
+            break;
+          case 'min':
+            expandedObjective.aggregator = values => Math.min(...values);
```
Comment (flekschas) [inline src/library.js]: Can you turn this into a utility function called `min` to `utils.js`? I am sure we might use it elsewhere.

```javascript
export const min = array => array.reduce((min, v) => v < min ? v : min, Infinity);
```

I've tested both your version and the reduce-based version and somehow the reduce-based version is 50% faster.

File: src/library.js [hunk 16]
```diff
@@ -1625,6 +1723,84 @@ const createPilingJs = (rootElement, initOptions = {}) => {
...
+            break;
+          case 'mean':
+          default:
+            expandedObjective.aggregator = values =>
```
Comment (flekschas) [inline src/library.js]: Let's use `mean` from above

File: src/library.js [hunk 17]
```diff
@@ -1625,6 +1723,84 @@ const createPilingJs = (rootElement, initOptions = {}) => {
...
+      } else {
+        expandedObjective.property = expandProperty(objective.property);
+
+        switch (objective.aggregator) {
+          case 'max':
+            expandedObjective.aggregator = values => Math.max(...values);
+            break;
+          case 'min':
+            expandedObjective.aggregator = values => Math.min(...values);
+            break;
```
Comment (flekschas) [inline src/library.js]: Let's add a `sum` condition :)

File: src/library.js [hunk 18]
```diff
@@ -1625,6 +1723,84 @@ const createPilingJs = (rootElement, initOptions = {}) => {
...
+          default:
+            expandedObjective.scale = scaleLinear;
+            break;
+        }
+
+        if (objective.inverse) {
+          expandedObjective.inverse = true;
+        } else {
+          expandedObjective.inverse = false;
+        }
```
Comment (flekschas) [inline src/library.js]: This can be simplified to `expandedObjective = !!objective.inverse`

File: src/library.js [hunk 19]
```diff
@@ -1625,6 +1723,84 @@ const createPilingJs = (rootElement, initOptions = {}) => {
...
+          default:
+            expandedObjective.aggregator = values =>
+              values.reduce(
+                (average, value) => average + value / values.length,
+                0
+              );
+            break;
+        }
+
+        switch (objective.scale) {
```
Comment (flekschas) [inline src/library.js]: What if someone provides a scale function?

File: src/library.js [hunk 20]
```diff
@@ -620,36 +617,128 @@ const createPilingJs = (rootElement, initOptions = {}) => {
...
-        layout.numRows = j + 1;
+        [x, y] = getPilePosition(pile);
 
-        const [x, y] = layout.ijToXy(
-          i,
-          j,
-          pile.graphics.width,
-          pile.graphics.height
-        );
+        if (x === null) {
```
[the remark this answers is not in the document]
Comment (eeeeenchanted) [reply src/library.js]: I guess you might forget that `positionPiles()` is only called once when initializing piles' position. If in `getPilePosition()` we don't dispatch `movePiles` action (which I think you are right), then we need to dispatch the action elsewhere.

**Comment by eeeeenchanted** [comment]
Sorry I didn't have much time to implement the 1D ordering and the `updateArrangement()` thing today. 
One thing you might forget is `positonPiles()` is only called once when initializing piles' position. If in getPilePosition() we don't dispatch movePiles action (which I think you are right), then we need to dispatch the action elsewhere.
